# Generated by Django 5.1.7 on 2025-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=100)),
                ('submission_id', models.CharField(max_length=100, unique=True)),
                ('code_content', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('time_limit', models.FloatField()),
                ('memory_limit', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
